config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "import_productions#index"
  post "import" => "import_productions#import"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inverter.rb
class Inverter < ApplicationRecord
  has_many :inverter_productions

  def self.identifiers
    distinct.pluck(:id)
  end
end

app/models/inverter_production.rb
class InverterProduction < ApplicationRecord
  validates :inverter_identifier, presence: true
  validates :datetime, presence: true
  validates :energy, presence: true

  belongs_to :inverter, foreign_key: :inverter_identifier

  def self.production(inverter_identifier, date)
    where(inverter_identifier: inverter_identifier, datetime: date.beginning_of_day..date.end_of_day)
    .group_by_hour(:datetime)
    .sum(:energy)
  end

  def self.total_production(date)
    where(datetime: date.beginning_of_day..date.end_of_day)
    .group_by_hour(:datetime)
    .sum(:energy)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/import_productions_controller.rb
class ImportProductionsController < ApplicationController
  before_action :set_selected_date, only: [ :index, :import ]

  def index
    identifier_data = Inverter.identifiers.map { |inverter_identifier|
      { name: inverter_identifier, data: InverterProduction.production(inverter_identifier, @selected_date) }
    }
    total_data = { name: "total", data: InverterProduction.total_production(@selected_date) }
    @production_data = identifier_data.append total_data
  end

  def import
    uploaded_file = params[:production_file]

    if uploaded_file.respond_to?(:read)
      uploaded_file.rewind
    else
      error_message = "The file sent is invalid"
      flash.now[:alert] = error_message
      render :index, status: :bad_request and return
    end

    csv_content = uploaded_file.read
    if csv_content.blank?
      error_message = "Empty CSV file"
      flash.now[:alert] = error_message
      render :index, status: :bad_request and return
    end

    csv_data = CSV.parse(csv_content, headers: true)
    required_headers = [ "identifier", "datetime", "energy" ]
    csv_headers = csv_data.headers
    missing_headers = required_headers - csv_headers
    unless missing_headers.empty?
      error_message = "Missing headers : #{missing_headers.join(', ')}"
      flash.now[:alert] = error_message
      render :index, status: :unprocessable_entity and return
    end

    begin
      ActiveRecord::Base.transaction do
        csv_data.each do |row|
          begin
            inverter = Inverter.find_or_create_by!(id: row["identifier"])
            InverterProduction.create!(
              inverter: inverter,
              datetime: DateTime.strptime(row["datetime"].to_s, "%d/%m/%y %H:%M"),
              energy: row["energy"]
            )
          rescue ActiveRecord::RecordInvalid => e
            Rails.logger.error "Missing data : #{e.message}"
            raise

          rescue Date::Error => e
            raise
          end
        end
      end
    rescue => e
      error_message = "CSV import error : #{e.message}"
      flash.now[:alert] = error_message
      render :index, status: :unprocessable_entity and return
    end

    flash.now[:notice] = "Successfully imported the CSV file."
    render :index, status: :created
  end

  private

  def set_selected_date
    @selected_date = params[:date] ? Date.parse(params[:date]) : Date.today
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/import_production/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Import production data</title>
  </head>

  <body>
    <h1>Import production data</h1>
    <p>Import a production data file below. (Only .csv accepted)</p>
    <%= form_with url: "/uploads", multipart: false do |form| %>
      <%= file_field_tag :production_file, accept: ".csv, text/csv" %>
    <% end %>          
  </body>
</html>

app/views/import_productions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% content_for :title, "Import production data" %>
  </head>

  <body>
    <h1>Import production data</h1>

    <% if flash[:alert] %>
      <div class="alert"><%= flash[:alert] %></div>
    <% end %>

    <% if flash[:notice] %>
      <div><%= flash[:notice] %></div>
    <% end %>

    <%= form_with url: import_path, multipart: true do |form| %>
      <%= form.label :production_file, "Import a production data file. (Only .csv accepted)" %>
      <%= file_field_tag :production_file, accept: ".csv, text/csv" %>
      <%= submit_tag "Submit" %>
    <% end %>

    <%= form_with url: root_path, method: :get do %>
      <%= label_tag :date, "Select a date" %>
      <%= date_field_tag :date, @selected_date %>
      <%= submit_tag "Submit" %>
    <% end %>

    <p>Selected date : <%= @selected_date.strftime("%d/%m/%Y") %></p>
    <% if @production_data.present? %>
      <%= area_chart @production_data, xtitle: "Time", ytitle: "Energy production" %>
    <% else %>
      <p>No data for the selected date.</p>
    <% end %>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Starterpack" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>